#!/bin/bash
# deploy - build and copy andrewdeorio.com source files
#
# Andrew DeOrio <awdeorio@umich.edu>

# Copy to server
rsync \
  --recursive \
  --verbose \
  --delete \
  html/ \
  awdeorio@web.eecs.umich.edu:public_html/
