#!/bin/bash
# test -- validate HTML
#
# Andrew DeOrio <awdeorio@umich.edu>

# Command line arguments
PROJECT_ROOT=`cd $(dirname $0) && pwd -P`

# Stop on errors and print commands
set -e
set -x

# Build
jekyll build

# Check HTML
html5validator --root ${PROJECT_ROOT}/_site
