#!/bin/bash

# Stop on errors
set -Eeuo pipefail

# Make sure publications list is up-to-date
cp html/index.html tmp.html
./build tmp.html
if ! diff -q html/index.html tmp.html > /dev/null; then
  echo "Error: publications list is out-of-date"
  rm -f tmp.html
  exit 1
else
  echo "Publications list is up-to-date"
  rm -f tmp.html
fi

# Make sure copyright year is up-to-date
COPYYEAR=$(grep -E '&copy; \d+ Andrew DeOrio' html/index.html | grep -Eo '\d+')
CURYEAR=$(date '+%Y')
if [ "$COPYYEAR" != "$CURYEAR" ]; then
  echo "Error: Copyright year ${COPYYEAR} in html/index.html is out-of-date"
  exit 1
else
  echo "Copyright year ${COPYYEAR} in html/index.html is up-to-date"
fi

# Print commands
set -x

# Validate HTML
html5validator --root html

# Check for bad links
linkchecker \
  --check-extern \
  --timeout 10 \
  --threads 100 \
  html
