#!/bin/bash
#
# Validate HTML

# Stop on errors
set -Eeuo pipefail

# Check if we're in the right directory
PROJECT_HOME=$(cd $(dirname $0) && pwd -P)
if [ $(pwd) != "$PROJECT_HOME" ]; then
  echo "Error: not in project root directory ${PROJECT_HOME}"
  exit 1
fi

# Make sure publications list is up-to-date
cp docs/index.html tmp.html
./build tmp.html
if ! diff -q docs/index.html tmp.html > /dev/null; then
  echo "Error: publications list is out-of-date"
  rm -f tmp.html
  exit 1
else
  echo "Publications list is up-to-date"
  rm -f tmp.html
fi

# Verify images are optimized for the web
IMAGES=$(ls docs/assets/images/*)

# File sizes should not be too big
for IMAGE in $IMAGES; do
  SIZE=$(du "$IMAGE" | awk '{print $1}')
  if [ "$SIZE" -ge 100 ]; then
    echo "Error: size exceeds 100 kB ${IMAGE} ${SIZE}"
    exit 1
  fi
done

# Images should not contain EXIF data.  It can reveal personal details like GPS
# location and cell phone serial number.
for IMAGE in $IMAGES; do
  EXIF=$(identify -format '%[EXIF:*]' "$IMAGE")
  if [ -n "$EXIF" ]; then
    echo "Error: EXIF data not allowed (try ImageOptim) ${IMAGE}"
    exit 1
  fi
done

# Print commands
set -x

# Make sure copyright year is up-to-date
YEAR=$(date '+%Y')
grep -q "&copy; 2009 - ${YEAR} Andrew DeOrio" docs/index.html

# Validate HTML
html5validator --root docs

# Check for bad links
linkchecker \
  --check-extern \
  --threads 100 \
  --ignore-url=https://umich.instructure.com/ \
  docs
